### ISSUE TITLE
Converting .es contracts to sql seems to put the contract id in the wrong column

### ISSUE THREAD

**Issue by adamplumb** [gmriggs/EmoteScript#3]
I've been tinkering with contracts and I noticed when I converted the Rufina weenie from es to sql, the contract stat (186) wasn't working when I re-imported.  Looking at the sql and comparing to the original, the 186 value was being put under the `amount` column not the `stat` column.  When I swapped the 186 from column 17 to column 15 in the sql file and re-imported then it worked.

[44890 Rufina.zip](https://github.com/gmriggs/EmoteScript/files/5977838/44890.Rufina.zip)

**Comment by gmriggs** [comment]
Fixed in https://github.com/gmriggs/EmoteScript/commit/ac20fc2410bf23e6635022380f565cceb3ee1f72

Thank you for reporting the issue
